# Site settings
title: Ironhee의 개발블로그
email: leechulhee95@gmail.com
author: ChulHee Lee
description: "Ironhee's Dev Blog"
baseurl: ""
url: "http://ironhee.github.io/"
google_analytics: "UA-48350213-1"
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 8
sass:
  compressed: true


#DISCUS
comments: true
